app/models/posts.py
from app import db
from datetime import datetime
from wtforms import ValidationError

class Posts(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text())
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def to_json(self):
        json_post={
            'post_id':self.id,
            'body':self.body,
            'timestamp':self.timestamp,
            'author_id':self.user_id
        }
        return json_post

    def from_json(json_post):
        body=json_post.get('body')
        if body is None or body=='':
            raise ValidationError('El post no tiene contenido')
        return Posts(body=body)

    def __repr__(self):
        return '<Post {}>'.format(self.body)

app/models/user.py
from app import db, login
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import AnonymousUserMixin, UserMixin
from app.models.role import Role, Permission
from hashlib import md5
from datetime import datetime

@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    #NEW 18-11-22
    name = db.Column(db.String(64))
    location = db.Column(db.String(64))
    about_me = db.Column(db.Text())
    member_since = db.Column(db.DateTime(), default=datetime.utcnow)
    last_seen = db.Column(db.DateTime(), default=datetime.utcnow)
    avatar = db.Column(db.String(300))
    #ENDNEW
    role_id = db.Column(db.Integer, db.ForeignKey("role.id"))
    posts = db.relationship("Posts", backref="author", lazy="dynamic")

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.role is None:
            if self.username == "marcelo":
                self.role = Role.query.filter_by(name="Administrator").first()
        if self.role is None:
            if self.role is None:
                self.role = Role.query.filter_by(default=True).first()
        url = 'https://secure.gravatar.com/avatar'
        hash = md5(self.email.lower().encode("utf-8")).hexdigest()
        self.avatar="{url}/{hash}?d={default}&s={size}&r={rating}".format(
            url=url, hash=hash, size=256, default="retro", rating="g"
        )
    def gravatar(self, size, default="retro", rating="g"):
        url = 'https://secure.gravatar.com/avatar'
        hash = md5(self.email.lower().encode("utf-8")).hexdigest()
        return "{url}/{hash}?d={default}&s={size}&r={rating}".format(
            url=url, hash=hash, size=size, default=default, rating=rating
        )

    def ping(self):
        self.last_seen = datetime.utcnow()
        db.session.add(self)
        db.session.commit()
        
    def __repr__(self):
        return "<User {}>".format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def can(self, perm):
        return self.role is not None and self.role.has_permission(perm)

    def is_administrator(self):
        return self.can(Permission.ADMIN)


class AnonymousUser(AnonymousUserMixin):
    def can(self, permissions):
        return False

    def is_administrator(self):
        return False


login.anonymous_user = AnonymousUser

app/routes/index.py
from datetime import datetime
from urllib.parse import urlparse
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from app.forms import LoginForm, PostForm, RegistrationForm
from app.models.posts import Posts
from app.models.role import Permission
from app import db
from app.models.user import User
from app.permisos import admin_required, permission_required

index_scope=Blueprint("index",__name__)


@index_scope.route('/',methods=["GET","POST"])
@index_scope.route('/index',methods=["GET","POST"])
@login_required
def index():
    form=PostForm()
    if current_user.can(Permission.WRITE) and form.validate_on_submit():
        post = Posts(body=form.body.data, author=current_user._get_current_object())
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('index.index'))
    posts = Posts.query.order_by(Posts.timestamp.desc()).all()
    return render_template("index.html",title="Home" ,form = form, posts = posts, WRITE = Permission.WRITE)

@index_scope.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()

@index_scope.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index.index'))
    form=LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Nombre de usuario o password incorrecto')
            return redirect(url_for('index.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or urlparse(next_page).netloc != '':
            next_page = url_for('index.index')
        return redirect(next_page)
    return render_template('login.html',title="Login",form=form)

@index_scope.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index.index'))

@index_scope.route('/register',methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Felicitaciones, es usted ahora un usuario registrado!')
        return redirect(url_for('index.login'))
    return render_template('register.html', title='Register', form=form)

@index_scope.route('/admin')
@login_required
@admin_required
def for_admins_only():
    return "Para admins!"

@index_scope.route('/moderate')
@login_required
@permission_required(Permission.MODERATE)
def for_moderators_only():
    return "Para comentarios de moderadores!"

app/routes/post.py
from datetime import datetime
from flask_login import current_user, login_required
from app import db,auth
from flask import flash, g, jsonify, redirect, render_template, request, url_for,Blueprint
from app.forms import PostForm
from app.models import Posts
from app.models.role import Permission
from app.models.user import User
from app.permisos import permission_required_rest

post_scope=Blueprint("post",__name__)

@post_scope.route('/editar-post/<int:id>',methods=['GET','POST'])
@login_required
def editar_post(id):
    post = Posts.query.filter_by(id=id).first_or_404()
    if current_user.id==post.user_id:
        form=PostForm()
        if form.validate_on_submit():
            post.body=form.body.data
            #post.timestamp=datetime.utcnow()
            db.session.add(post)
            db.session.commit()
            flash('Tu post se actualizó correctamente.')
            return redirect(url_for('index.index'))
        form.body.data=post.body
        return render_template('edit-post.html',form=form)
    return redirect(url_for('index.index'))


@auth.verify_password
def verify_password(email, password):
    if email == '':
        return False
    user = User.query.filter_by(email = email).first()
    if not user:
        return False
    print(user.email)
    g.current_user = user
    print(g.current_user)
    return user.check_password(password)

@post_scope.route('/postJson/',methods=['POST'])
@auth.login_required
@permission_required_rest(Permission.WRITE)
def new_post():
    post=Posts.from_json(json_post=request.json)
    post.author=g.current_user
    db.session.add(post)
    db.session.commit()
    return jsonify(post.to_json()), 201, {'Location': url_for('.post_detail', id=post.id)}

@post_scope.route("/post-detail/<id>")
def post_detail(id):
    return id

app/routes/user.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_required
from app.forms import EditProfileForm
from app import db
from app.models.user import User
from app.permisos import admin_required

user_scope=Blueprint("user",__name__)


@user_scope.route('/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts= user.posts.all()
    return render_template('user.html',title="Profile" ,user=user, posts=posts)

@user_scope.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('Tu perfil se actualizó correctamente.')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('edit-profile.html',title="Edit Profile", form=form)

@user_scope.route('/edit-profile/<username>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(username):
    form = EditProfileForm()
    user = User.query.filter_by(username=username).first_or_404()
    if form.validate_on_submit():
        user.name = form.name.data
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        db.session.commit()
        flash('Su perfil se actualizó correctamente.')
        return redirect(url_for('.user', username=user.username))
    form.name.data = user.name
    form.location.data = user.location
    form.about_me.data = user.about_me
    return render_template('edit-profile.html',title="Edit Profile", form=form)

app/templates/_post.html
<ul class="posts">
    <li class="post">
        <div>
            <a href="{{url_for('user.user', username=post.author.username)}}">
                <img class ="img-post" src="{{post.author.gravatar(size=40)}}" />
            </a>
        </div>
        <div class="post-card">
            <div class="post-info">
                <div class="post-author">
                    <a href="{{url_for('user.user', username=post.author.username)}}">
                    {{ post.author.username }}
                    </a>
                </div>
                <div class="post-date">
                    {{ moment(post.timestamp).fromNow() }}
                </div>
            </div>
            <div class="post-body">
                <div class="post-author">
                    {{ post.body }}
                </div>
                {% if current_user.username==post.author.username %}
                    <div class="post-date">
                        <a href="{{ url_for('post.editar_post',id=post.id ) }}" class="btn btn-primary" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
                            Editar
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
    </li>
</ul>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% if title %}
    <title>{{ title }} - Blog</title>
    {% else %}
    <title>Welcome to my Blog</title>
    {% endif %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
    {{ moment.include_moment() }}
    {{ moment.locale("es") }}
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-dark bg-dark navbar-expand-lg mt-3">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Your Blog</a>
          
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" href="{{ url_for('index.index' ) }}">Home</a>
              </li>
              {% if not current_user.is_anonymous %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('user.user', username=current_user.username) }}">Profile</a>
                </li>
              {% endif %}
            </ul>
            <span class="navbar-text">
                {% if current_user.is_anonymous %}
                <a class="nav-link " href="{{ url_for('index.login') }}">Login</a>
                {% else %}
                <a class="nav-link" href="{{ url_for('index.logout') }}">Logout</a>
                {% endif %}
            </span>
          </div>
        </div>
      </nav>
      <hr />
      {% with messages = get_flashed_messages() %} {% if messages %}
        <div class="alert alert-warning" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
      {% endif %} {% endwith %} 
      
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

app/templates/edit-post.html
{% extends "base.html"%}
{%block content%}
    <h1>Editar Post</h1>
    <form action="" method="post" novalidate>
        <p>
            <label for="name">Escrito Por:</label><br>
            <input id="name" maxlength="64" minlength="0" name="name" size="32" type="text" value="{{ current_user.username }}" disabled>
        </p>
        {{ form.hidden_tag() }}
        <p class="form-body">
          {{ form.body.label }}<br />
          {{ form.body(size=32) }} {% for error in form.body.errors %}
          <span style="color: red">[{{ error }}]</span>
          {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
      </form>
{% endblock %}

app/templates/edit-profile.html
{% extends "base.html"%}
{%block content%}
    <h1>Editar perfil</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        
        <p>
        {{ form.name.label }}<br />
        {{ form.name(size=32) }}
        {% for error in form.name.errors %}
        <span style="color: red">[{{ error }}]</span>
        {% endfor %}
        </p>
        <p>
        {{ form.location.label }}<br />
        {{ form.location(size=32) }}
        {% for error in form.location.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}

        </p>
        <p>
            {{ form.about_me.label }}<br />
            {{ form.about_me(cols=50,rows=4) }}
            {% for error in form.about_me.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}

        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Bienvenido!</h1>
    <h3>Hi, {{ current_user.username }}!</h3>
    <div>
        {% if current_user.can(WRITE) %}
        <form action="" method="post" novalidate>
          {{ form.hidden_tag() }}
          <p class="form-body">
            {{ form.body.label }}<br />
            {{ form.body(size=32) }} {% for error in form.body.errors %}
            <span style="color: red">[{{ error }}]</span>
            {% endfor %}
          </p>
          <p>{{ form.submit() }}</p>
        </form>
        {% endif %}
    </div>
    {% for post in posts %}
        {% include '_post.html'   %}
    {% endfor %}
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Iniciar Sesión</h1>
    <hr>
    <p>Nuevo usuario? <a href="{{ url_for('index.register') }}">Click para Registrarte!</a></p>
    <hr>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>    
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block content %}
    <h1>Register</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block content %}
    <div>
        {% if user == current_user %}
        {% endif %}
        <div class="profile">
            {% if user.avatar %}
                <img class="img" src="{{ user.avatar }}"/>
            {% else %}
                <img class="img" src="{{ user.gravatar(size=256) }}"/>
            {% endif %}
            <div class="info">
                <h1>{{ user.username }}</h1>
                {% if user.name or user.location %}
                    <p>
                        {% if user.name %}{{ user.name }}{% endif %} 
                        {% if user.location %} De
                        <a href="http://maps.google.com/?q={{ user.location }}" target="_blank" >
                        {{ user.location }}
                        </a>
                        {% endif %}
                    </p>
                {% endif %} 

                {% if current_user.is_administrator() %}
                    <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
                {% endif %} 

                {% if user.about_me %}
                    <p>{{ user.about_me }}</p>
                {% endif %}

                <p>Miembro desde: {{ moment(user.member_since).format('LL') }}.</p>
                
                {% if user.last_seen %}
                    <p>Ultimo ingreso: {{moment(user.last_seen).fromNow() }}.</p>
                {% endif %}
                
                {% if current_user.is_administrator() %}
                    <a class="btn btn-success" href="{{ url_for('.edit_profile_admin',username=user.username) }}">
                        Editar Perfil
                    </a>
                {% elif current_user.username == user.username %}
                    <a class="btn btn-success" href="{{ url_for('.edit_profile') }}">
                        Editar Perfil
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
    <hr>
    {% for post in posts %}
        {% include '_post.html'   %}
    {% endfor %}
{% endblock %}